version: 1.0
os: linux
files:
 - source: .
   destination: /home/ubuntu/starfile
hooks:
  AfterInstall:
   - location: scripts/install
     timeout: 300
     runas: root
  ApplicationStart:
   - location: scripts/waitress_server
     timeout: 300
     runas: root