name: CI/CD Pipeline
on:
  push:
    branches: [ master ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      # Step 1
      - uses: actions/checkout@v2
      # Step 2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      # Step 3
      - name: Install dependencies
        run: pip install -r requirements.txt
      # Step 4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          #role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          #role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
          #role-duration-seconds: 1200
          #role-session-name: MySessionName
          
      # Step 5
      - name: Build Application and Run unit Test
        run: python app.py & python -m pytest -v
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION_NAME: us-east-1
          AWS_BUCKET_NAME: fhostbucket

  Deploy:
    runs-on: ubuntu-latest
    needs: [Build]
    if: github.ref == 'refs/heads/master'
    steps:
     # Step 1
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.RSA }} 
          known_hosts: 'placeholder'
      # Step 2
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
     # Step 3
      - name: Rsync
        uses: up9cloud/action-rsync@v1.1
        env:
          HOST: ${{ secrets.HOST }}
          KEY: ${{ secrets.RSA }}
          TARGET: /app/hello-service/

          VERBOSE: true
          USER: ubuntu
          # PORT: 2222 # no need to set this, because of $SSH_ARGS
          ARGS: -az --exclude=/.git/
          SSH_ARGS: '-p 2222 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
          SOURCE: ./

          PRE_SCRIPT: |
            echo start at:
            date -u
          POST_SCRIPT: "echo done at: && date -u"
    