name: CI/CD Pipeline
on:
  push:
    branches: [ master ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      # Step 1
      - uses: actions/checkout@v2
      # Step 2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      # Step 3
      - name: Install dependencies
        run: pip install -r requirements.txt          
      # Step 4
      - name: Build Application #and Run unit Test
        run: timeout 30 python app.py #& python -m pytest -v

  Deploy:
    runs-on: ubuntu-latest
    needs: [Build]
    if: github.ref == 'refs/heads/master'
    steps:
     # Step 1
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.RSA }} 
          known_hosts: 'placeholder'
      # Step 2
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
     # Step 3
      - name: Cloning git via ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: Dr3amsavior
          key: ${{ secrets.RSA }}
          port: 22
          script: rm -rf starfile/ && git clone git@github.com:matheusoliveira3631/starfile.git && sudo pip install -r starfile/requirements.txt && sudo systemctl restart starfile.service
    